---
title: "Process for Reading and Cleaning Samsung S3 data"
output: html_document
date: "2025-03-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Reading features and labels
- The features.txt file represents the data frame column names. 
- The activity_labels.txt file represents the test string values corresponding to the numeric coded activity in the y-test and y-train data files  
- Each were read as plain text files into character vectors
- The labels vector was split and the first element discarded  
- The first element of the features was retained initially so that the column names would match the underlying data in the x-test and x-train files  

### Reading the data (same process utilized for test and train data)
- The subject and y (activity) values files contained a single value on each line and were read into a character vector and converted to numeric values  
- The x value file contained data formated a fixed width of 16 characters for each line of 561 variables (features) and were read using the fixed width format function (read.fwf)  
- The read.fwf function recognized the data as numeric and did not require conversion

### Combined subjects, labels and features (same process for test and train data)
- Utilzed cbind to combine subject and label numeric vectores with the features data frame in a new data frame named <test | train>Data  
- Added the column names from the features character vector. 
- Added a column named dataset at the end of the data frame containing the name TEST or TRAIN they were loaded from  
- Removed (deleted) the temporary objects the subjects, labels and features were read into  

### Combined the test and train dataframes  
- Utilized rbind to combine the test and train dataframes  
- Removed (deleted) the test and train dataframes

### Transformed the activity and dataset columns
- Created a new column containing the activity label text strings corresponding to the values in the labels (y value) data
- Converted the new activity and dataset columns to factor variables

### Selected the subset of columns for mean and standard deviation
- Utilized the dplyr select function and a regular expression to select columns that contained mean or std

### Altered column (feature) names to more friendly variable names
- Removed the leading numeric values by splitting the column names and retaining the second element when preceded by a numeric value  
- Removed the parentheses if present in the columns name  

### Create separate summary dataframe of column mean values
- Utilized sequential select to remove dataset column, group by activity and subjectid and summarize the rest of the columns using the mean function. 
- Wrote the dataframe to the text file summary.txt




